management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
  configs:
    default:
      failure-rate-threshold: 33
  instances:
    test:
      base-config: default
      
resilience4j.retry:
  configs:
    default:
      max-retry-attempts: 33
  instances:
    test:
      base-config: default
      
resilience4j.bulkhead:
  configs:
    default:
      max-concurrent-calls: 33
  instances:
    test:
      base-config: default
      
resilience4j.thread-pool-bulkhead:
  configs:
    default:
      max-thread-pool-size: 33
  instances:
    test:
      base-config: default
      
resilience4j.ratelimiter:
  configs:
    default:
      limit-for-period: 33
  instances:
    test:
      base-config: default
      register-health-indicator: true
