resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 66
      waitDurationInOpenState: 2s
      ringBufferSizeInClosedState: 1000
      ringBufferSizeInHalfOpenState: 10

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 66
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 66

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 66

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 66
      limitRefreshPeriod: 1s
      timeoutDuration: 0
