resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 10
      waitDurationInOpenState: 2s
      ringBufferSizeInClosedState: 1000
      ringBufferSizeInHalfOpenState: 10

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 10
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 10

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
